apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    app: builder
  namespace: envoy
spec:
  restartPolicy: Never
  containers:
    - name: builder
      image: quay.io/maistra-dev/maistra-builder:2.2
      env:
      - name: CI
        value: "true"
      - name: BAZEL_DISK_CACHE
        value: /tmp/cache
      command: ["/bin/bash"]
      args: ["-c", "tail -f /dev/null"]
      resources:
        limits:
          memory: "8Gi"
          cpu: "8"
        requests:
          memory: "4Gi"
          cpu: "4"
